on:
  release:
    types:
      - published
  
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions/checkout@v4

      - uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: branch@master

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m release -p windows -v -y

      - run: |
          xmake -w -y

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-windows-x64-${{ github.sha }}
          path: |
            bin/DLL/

      - uses: actions/upload-artifact@v4
        with:
          name: PDB
          path: |
            bin/PDB/

      - uses: actions/upload-artifact@v4
        with:
          name: SDK
          path: |
            bin/SDK/

  upload-to-release:
    needs:
      - build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Mod
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-windows-x64-${{ github.sha }}
          path: release/Mod/

      - name: Download PDB
        uses: actions/download-artifact@v4
        with:
          name: PDB
          path: release/PDB/

      - name: Download SDK artifact
        uses: actions/download-artifact@v4
        with:
          name: SDK
          path: release/SDK/

      - name: Copy additional files
        run: |
          cp LICENSE README.md release/Mod/

      - name: Archive release
        run: |
          cd release/Mod
          zip -r ../${{ github.event.repository.name }}-windows-x64.zip *
          cd ..

      - name: Archive SDK directory
        run: |
          cd release/SDK
          zip -r ../SDK.zip *
          cd ..

      - name: Calculate SHA256
        id: calculate-sha256
        run: |
          echo release=$(sha256sum release/SDK.zip | awk '{print $1}') >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          append_body: true
          body: |
            | File | SHA256 |
            | ---- | ------ |
            | SDK.zip | ${{ steps.calculate-sha256.outputs.release }} |
          files: |
            release/${{ github.event.repository.name }}-windows-x64.zip
            release/PDB/${{ github.event.repository.name }}.pdb 
            release/SDK.zip
